import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowUpRight, CheckCircle2, Clock3, Filter, LifeBuoy, LogOut, Plus, Search, ShieldCheck, Ticket, UserRound } from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000/api';
const demoAccounts = { STUDENT: ['student@edusupport.demo', 'demo123'], STAFF: ['staff@edusupport.demo', 'demo123'], MANAGER: ['manager@edusupport.demo', 'demo123'] };
const statusLabels = { OPEN: 'Open', ASSIGNED: 'Assigned', IN_PROGRESS: 'In progress', PENDING_STUDENT: 'Waiting on student', RESOLVED: 'Resolved', CLOSED: 'Closed', REOPENED: 'Reopened' };

async function request(path, options = {}) {
  const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } });
  if (!response.ok) throw new Error((await response.json()).detail || 'Something went wrong');
  return response.json();
}

function Login({ onLogin }) {
  const [form, setForm] = useState({ email: demoAccounts.STUDENT[0], password: demoAccounts.STUDENT[1] });
  const [error, setError] = useState('');
  const submit = async (event) => { event.preventDefault(); setError(''); try { const response = await fetch(`${API}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ username: form.email, password: form.password }) }); if (!response.ok) throw new Error((await response.json()).detail || 'Something went wrong'); onLogin(await response.json()); } catch (err) { setError(err.message); } };
  return <main className="login-shell"><section className="login-intro"><div className="brand-mark"><LifeBuoy size={20} /> EduSupport</div><p className="eyebrow">Student services, without the chase</p><h1>Every question deserves a clear next step.</h1><p className="intro-copy">A calm support workspace for students, service teams, and the people keeping the whole system moving.</p><div className="intro-stats"><span><strong>1h</strong> urgent response</span><span><strong>24/7</strong> visibility</span></div></section><form className="login-card" onSubmit={submit}><span className="eyebrow">Welcome back</span><h2>Sign in to your workspace</h2><label>Email<input value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} type="email" /></label><label>Password<input value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} type="password" /></label>{error && <p className="error">{error}</p>}<button className="primary" type="submit">Open workspace <ArrowUpRight size={16} /></button><div className="demo-access"><span>Demo access</span><div>{Object.entries(demoAccounts).map(([role, account]) => <button type="button" key={role} onClick={() => setForm({ email: account[0], password: account[1] })}>{role.toLowerCase()}</button>)}</div></div></form></main>;
}

function App() {
  const [session, setSession] = useState(() => JSON.parse(localStorage.getItem('edusupport-session') || 'null'));
  if (!session) return <Login onLogin={data => { localStorage.setItem('edusupport-session', JSON.stringify(data)); setSession(data); }} />;
  return <Workspace session={session} onLogout={() => { localStorage.removeItem('edusupport-session'); setSession(null); }} />;
}

function Workspace({ session, onLogout }) {
  const [tickets, setTickets] = useState([]); const [metrics, setMetrics] = useState({}); const [search, setSearch] = useState(''); const [filter, setFilter] = useState(''); const [selected, setSelected] = useState(null); const [showCreate, setShowCreate] = useState(false); const [error, setError] = useState('');
  const headers = { Authorization: `Bearer ${session.access_token}` };
  const load = async () => { try { const params = new URLSearchParams(); if (search) params.set('search', search); if (filter) params.set('status', filter); const [list, dashboard] = await Promise.all([request(`/tickets?${params}`, { headers }), request('/dashboard', { headers })]); setTickets(list); setMetrics(dashboard); } catch (err) { setError(err.message); } };
  useEffect(() => { load(); }, [search, filter]);
  const updateTicket = async (id, body) => { await request(`/tickets/${id}`, { method: 'PATCH', headers, body: JSON.stringify(body) }); await load(); if (selected) setSelected(await request(`/tickets/${id}`, { headers })); };
  const roleName = session.user.role === 'MANAGER' ? 'Manager' : session.user.role === 'STAFF' ? 'Support desk' : 'Student';
  return <div className="app-shell"><aside><div className="brand-mark"><LifeBuoy size={20} /> EduSupport</div><div className="side-role"><ShieldCheck size={16} /><span>{roleName}<small>{session.user.name}</small></span></div><nav><a className="active"><Activity size={17} /> Overview</a><a><Ticket size={17} /> Tickets <b>{metrics.total || 0}</b></a><a><Clock3 size={17} /> SLA watch</a></nav><button className="logout" onClick={onLogout}><LogOut size={16} /> Sign out</button></aside><main className="content"><header><div><p className="eyebrow">Thursday, 25 September 2026</p><h1>{session.user.role === 'STUDENT' ? 'Your support desk' : 'Operations overview'}</h1></div><div className="user-chip"><span>{session.user.name.split(' ').map(n => n[0]).join('')}</span><div>{session.user.name}<small>{session.user.role}</small></div></div></header>{error && <div className="error-banner">{error}</div>}<section className="metric-grid"><Metric label="All tickets" value={metrics.total || 0} icon={<Ticket />} /><Metric label="Open" value={metrics.open || 0} icon={<Clock3 />} tone="amber" /><Metric label="In progress" value={metrics.in_progress || 0} icon={<Activity />} tone="blue" /><Metric label="Resolved" value={metrics.resolved || 0} icon={<CheckCircle2 />} tone="green" /><Metric label="SLA breached" value={metrics.breached || 0} icon={<ShieldCheck />} tone="red" /></section><section className="section-head"><div><p className="eyebrow">Live queue</p><h2>{session.user.role === 'STUDENT' ? 'Your recent requests' : 'Tickets needing attention'}</h2></div>{session.user.role === 'STUDENT' && <button className="primary compact" onClick={() => setShowCreate(true)}><Plus size={16} /> New ticket</button>}</section><div className="toolbar"><div className="search"><Search size={17} /><input placeholder="Search by subject" value={search} onChange={e => setSearch(e.target.value)} /></div><div className="filter"><Filter size={16} /><select value={filter} onChange={e => setFilter(e.target.value)}><option value="">All statuses</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></div><div className="ticket-list">{tickets.map(ticket => <TicketRow key={ticket.id} ticket={ticket} onClick={() => request(`/tickets/${ticket.id}`, { headers }).then(setSelected)} />)}{!tickets.length && <div className="empty">No tickets match this view.</div>}</div></main>{selected && <TicketPanel ticket={selected} user={session.user} onClose={() => setSelected(null)} onUpdate={updateTicket} headers={headers} />} {showCreate && <CreateTicket onClose={() => setShowCreate(false)} onCreated={() => { setShowCreate(false); load(); }} headers={headers} />}</div>;
}

function Metric({ label, value, icon, tone = '' }) { return <div className={`metric ${tone}`}><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong></div>; }
function TicketRow({ ticket, onClick }) { const breached = !['RESOLVED', 'CLOSED'].includes(ticket.status) && new Date(ticket.due_at) < new Date(); return <button className="ticket-row" onClick={onClick}><div className="ticket-id">EDU-{String(ticket.id).padStart(4, '0')}</div><div className="ticket-main"><strong>{ticket.subject}</strong><span>{ticket.category} · Updated {new Date(ticket.updated_at).toLocaleDateString()}</span></div><span className={`priority ${ticket.priority.toLowerCase()}`}>{ticket.priority}</span><span className="status-pill">{statusLabels[ticket.status]}</span><span className={`sla ${breached ? 'breached' : ''}`}>{breached ? 'Breached' : 'On track'}</span><ArrowUpRight size={17} /></button>; }
function TicketPanel({ ticket, user, onClose, onUpdate, headers }) { const [comment, setComment] = useState(''); const addComment = async () => { if (!comment.trim()) return; await request(`/tickets/${ticket.id}/comments`, { method: 'POST', headers, body: JSON.stringify({ body: comment }) }); setComment(''); }; return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer" onClick={e => e.stopPropagation()}><button className="close" onClick={onClose}>×</button><p className="eyebrow">EDU-{String(ticket.id).padStart(4, '0')} · {ticket.category}</p><h2>{ticket.subject}</h2><p className="drawer-description">{ticket.description}</p><div className="drawer-controls"><span className={`priority ${ticket.priority.toLowerCase()}`}>{ticket.priority}</span>{user.role !== 'STUDENT' && <select value={ticket.status} onChange={e => onUpdate(ticket.id, { status: e.target.value })}>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>}</div><div className="timeline"><h3>Activity</h3>{ticket.activity.map(item => <div className="timeline-item" key={item.id}><span></span><div>{item.action}<small>{new Date(item.created_at).toLocaleString()}</small></div></div>)}</div><div className="comment-box"><textarea value={comment} onChange={e => setComment(e.target.value)} placeholder="Add a reply or internal note..." /><button className="primary compact" onClick={addComment}>Post update</button></div></aside></div>; }
function CreateTicket({ onClose, onCreated, headers }) { const [form, setForm] = useState({ subject: '', description: '', category: 'Fees', priority: 'MEDIUM' }); const submit = async e => { e.preventDefault(); await request('/tickets', { method: 'POST', headers, body: JSON.stringify(form) }); onCreated(); }; return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><button type="button" className="close" onClick={onClose}>×</button><p className="eyebrow">New request</p><h2>Tell us what happened</h2><label>Subject<input required minLength="5" value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })} /></label><label>Category<select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{['Fees', 'Attendance', 'ID Card', 'Certificate', 'Documents', 'Examination', 'Hostel', 'Transport', 'Technical', 'Other'].map(v => <option key={v}>{v}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value })}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select></label><label>Description<textarea required minLength="10" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><button className="primary" type="submit">Submit ticket <ArrowUpRight size={16} /></button></form></div>; }
createRoot(document.getElementById('root')).render(<App />);